[project]
name = "py"
version = "0.1.0"
description = "Simple Python environment for running Neovim plugins"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "neovim>=0.3.1",
    "pynvim>=0.5.2",
    "pyvim>=3.0.3",
]
