services:
  nvim_dev:
    container_name: nvim_dev
    image: andyandyandyandy2023/nvim-dev:latest
    ports:
      - "2223:22"
    volumes:
      # - ~/mnt/cinfin/aweaver:/root/cinfin/aweaver
      - ./:/root
    tty: true
    stdin_open: true