# .github/workflows/push_to_dockerhub.yml
#
# This workflow builds a multi-architecture Docker image using Docker Buildx.
# It supports 64-bit architectures (e.g., amd64 and arm64) and pushes the built image
# to DockerHub with appropriate tags.
#
# Prerequisites:
#   - DockerHub credentials stored in repository secrets:
#       DOCKERHUB_USERNAME and DOCKERHUB_TOKEN.
#
# The workflow is triggered on any push to the main branch.
name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  log-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log GitHub context
        run: echo "$GITHUB_CONTEXT"

      - name: Log GitHub event
        run: echo "$GITHUB_EVENT"

      - name: Log ls and pwd
        run: |
          ls -lah
          pwd -P

  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          file: ./devcontainer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvim-dev:latest
          platforms: linux/amd64

  build-arm64:
    runs-on: ubuntu-latest
    steps:    
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          file: ./devcontainer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvim-dev:latest
          platforms: linux/arm64

  build-armv8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          file: ./devcontainer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvim-dev:latest
          platforms: linux/arm/v8

  build-amd64-v3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          file: ./devcontainer/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvim-dev:latest
          platforms: linux/amd64/v3

# End of file
